### Persist request
POST localhost:8080/api/v1/request
Content-Type: application/json

{
  "service": "A",
  "roaming": false,
  "phoneNumber": "+1234567890",
  "rsu": 2
}

### Find Report by number
GET localhost:8080/api/v1/report?phoneNumber=+12345678901