# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# The main goal here will be run all tests in order to ensure the quality of code

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Set up MongoDB
      uses: supercharge/mongodb-github-action@v1
      with:
          mongodb-version: 'latest'

    - name: Build and Test with Maven
      env:
        MONGODB_URI: mongodb://localhost:27017/wise-database
      run: |
        mvn clean test -Dmongodb.uri=$MONGODB_URI    

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Build and Test with Maven
      run: mvn clean test
